combine add-assignee and check-changelog jobs into one workflow

diff --git a/mex-{{ cookiecutter.project_name }}/.github/workflows/reviewing.yml b/mex-{{ cookiecutter.project_name }}/.github/workflows/reviewing.yml
--- a/mex-{{ cookiecutter.project_name }}/.github/workflows/reviewing.yml
+++ b/mex-{{ cookiecutter.project_name }}/.github/workflows/reviewing.yml
@@ -5,13 +5,16 @@ on:
     types:
       - opened
       - reopened
+      - synchronize
+  workflow_dispatch:
 
 concurrency:
   group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
   cancel-in-progress: true
 
 jobs:
-  assignee:
+  add-assignee:
+    name: Add assignee
     runs-on: ubuntu-latest
     timeout-minutes: 10
     permissions:
@@ -47,4 +50,35 @@ jobs:
           {% raw -%}
           gh pr edit ${{ github.event.pull_request.html_url }} \
           --add-assignee "${{ steps.resolve.outputs.user_name }}"
+          {%- endraw %}
+
+  check-changelog:
+    name: Check changelog
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    permissions:
+      contents: read
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          fetch-depth: 0
+
+      - name: Check for CHANGELOG.md changes
+        run: |
+          {% raw -%}
+          if [ "${{ github.actor }}" = "RKIMetadataExchange" ]; then
+            echo "Actor is 'RKIMetadataExchange'. Skipping changelog check."
+            exit 0;
+          fi
+
+          if git diff --quiet "origin/${{ github.base_ref }}"...HEAD -- "CHANGELOG.md"; then
+            echo "Error: The CHANGELOG.md has not been modified."
+            echo "Please add your changes to CHANGELOG.md before merging."
+            exit 1
+          else
+            echo "CHANGELOG.md has been modified."
+            exit 0
+          fi
           {%- endraw %}
